//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matieres
    {
        public string codeMat { get; set; }
        public string designation { get; set; }
        public string niveau { get; set; }
        public string semestre { get; set; }
        public string code_Fil { get; set; }
    }
}
