//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class biblioEntities : DbContext
    {
        public biblioEntities()
            : base("name=biblioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eleves> eleves { get; set; }
        public virtual DbSet<filieres> filieres { get; set; }
        public virtual DbSet<matieres> matieres { get; set; }
        public virtual DbSet<moyennes> moyennes { get; set; }
        public virtual DbSet<notes> notes { get; set; }
    }
}
