//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moyennes
    {
        public string codeElev { get; set; }
        public string codeF { get; set; }
        public string niveau { get; set; }
        public double Moyenne_Ann { get; set; }
    }
}
